using System;
using System.Linq;

namespace DndCore
{
	public enum PlayerProperty
	{
		NameHeadshot,
		RaceClass,
		Level,
		Inspiration,
		ExperiencePoints,
		Alignment,
		Strength,
		Dexterity,
		Constitution,
		Intelligence,
		Wisdom,
		Charisma,
		ArmorClass,
		Initiative,
		Speed,
		HitPointsTempHitPoints,
		DeathSaves,
		HitDice,
		ProficiencyBonus,
		Perception,
		GoldPieces,
		SavingStrength,
		SavingDexterity,
		SavingConstitution,
		SavingIntelligence,
		SavingWisdom,
		SavingCharisma,
		SkillsAcrobatics,
		SkillsAnimalHandling,
		SkillsArcana,
		SkillsAthletics,
		SkillsDeception,
		SkillsHistory,
		SkillsInsight,
		SkillsIntimidation,
		SkillsInvestigation,
		SkillsMedicine,
		SkillsNature,
		SkillsPerception,
		SkillsPerformance,
		SkillsPersuasion,
		SkillsReligion,
		SkillsSlightOfHand,
		SkillsStealth,
		SkillsSurvival,
		Load,
		Weight
	}
}
